[metadata]
title = "Feature Test"
publisher = "AndreGarzia.com"
date = 2021-02-07T12:00:00Z
identifier = "https://little.webby.press/samples/feature-test.html"
cover = "images/cover.jpg"

[author]
name = "Andre Alves Garzia"

[toc]
label = "h1"
match = "first"

[book]
chapters = [
  "sample-markdown.md",
  "sample-asciidoctor.adoc",
  "sample-textile.textile"
]
